language: java
jdk:
  - oraclejdk8

sudo: false

cache:
  directories:
    - $HOME/.m2

notifications:
  email: false

before_install:
  - ulimit -u 65535

script:
  - mvn -Dmaven.test.skip=true compile
