sudo: false
language: java
jdk:
  - oraclejdk8

env:
  global:
  - MVN_SHARED_CACHE=$HOME/.m2
cache:
  directories:
    - "${MVN_SHARED_CACHE}"

before_install:
  - mkdir -p ${MVN_SHARED_CACHE}
  
install: gradle assemble -Dbuild.snapshot=false

script: gradle core:test -Dbuild.snapshot=false

before_deploy:
  - export TARBALL=$(ls distribution/tar/build/distributions/elassandra-*.tar.gz)
  - export ZIPBALL=$(ls distribution/zip/build/distributions/elassandra-*.zip)
  - export DEBPKG=$(ls distribution/deb/build/distributions/elassandra_*.deb)
  - export RPMPKG=$(ls distribution/rpm/build/distributions/elassandra-*.rpm)

deploy:
  - provider: releases
    overwrite: true
    draft: true
    api_key:
      secure: CtTEWfptldC5QoeOl+nseF3uVyjmJglxnk7Mv9qHH4w24/R3GI6Q4TsJxLjp0yf0+ltnE6vg1wERIY5HiE0jvIM3l/ZFUKEFE/f6h9yvmUWFaQD2yOKNKB4fvqYfX0KZWDF0YotMi3bweegrXS66fu5s3jfjXH6DLNmzGjv0cAcumdppJDUOmETktIlWr86KKRJMuYTXiJIe4CXLfgkZEEY7cYsHysrfJvYBPYka9n4kzlcj0PB3Ux4mT8flMLIzfFymnxGWXv2Ubf1DJpCtfyb65OqFqMcWL1NjL+T2Z3OoWI5QgMtoapHX6Z6xuoBQbnN+PR5dq7pmUXJKXpoEsBzfMdv8FpiPS/NV1iRIEzgpab7nIuQ00QDkTA6R+69ugGpwOnaceoNIMnjOQjfaAHT6Xfc4vByFhhZxSp1H6hmdhtaksE1U1w4HMfHnejXTLCNMnsnbmDW1Tygjyu/zI7t9lCeF5kpnbXDV+oBHKxGR6yBZjVbG49Y3IQY7WFoFUKBgkCgYWqFMnLzCwVaJfqTFjQHOzhp1vg+RTgAtTWhjeWKwm9HqSH+R6F6tbhwKdPCDOOdzEAksnwmqUqi4iz8vjTsoiU86WXgds3PDVk4IK6ZxGRJ/UabQz/krXgay1dWOBVRYr4FzP+a5VH7mEyjdW+3SBMztbTw48g65jEE=
    file:
      - "$TARBALL"
      - "$ZIPBALL"
      - "$DEBPKG"
      - "$RPMPKG"
    skip_cleanup: true
    on:
      tags: true
      repo: strapdata/elassandra5-rc
